### PR TITLE
Thumbnail auto delete fix

### PR DESCRIPTION
**Pull request by bipinkrish**
fixed the thumbline auto delete line of the code

### CODE REVIEW

**Comment by Nekmo** [comment]
what is the purpose of this PR? A feature is removed.

**Comment by bipinkrish** [comment]
> what is the purpose of this PR? A feature is removed.

what is the purpose of multiple files selction? if thumbnail is deleted after single file and leads to error.

**Comment by Nekmo** [comment]
Are you saying that uploading multiple files fails if the files have thumbnails?

**Comment by bipinkrish** [comment]
> Are you saying that uploading multiple files fails if the files have thumbnails?

yes, because thumbnail is getting deleted right after the first flle uploaded

**Comment by Nekmo** [comment]
Thanks for the warning @bipinkrish, but the solution is not to remove the feature. It must be fixed. I'm going to investigate it.

**Comment by bipinkrish** [comment]
> Thanks for the warning @bipinkrish, but the solution is not to remove the feature. It must be fixed. I'm going to investigate it.

i don't understand how deleting the user's image is a feature?

**Pull request closed without merging**
